[build]
  command = "npm run netlify-build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure the _next directory is correctly served
[[headers]]
  for = "/_next/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

# Handle Next.js image optimization routes
[[redirects]]
  from = "/_next/image*"
  to = "/_next/image*"
  status = 200

# Handle client-side routing and SPA functionality
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {HostName = "tokenizeme.ai"}
  force = false

# Handle client-side routing for Netlify subdomain
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {HostName = "netlify.app"}
  force = false 